FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt ./requirements.txt
RUN pip install --no-cache-dir -r requirements.txt
RUN python -m playwright install --with-deps chromium

COPY compute ./compute
COPY data_access ./data_access
COPY services ./services
COPY pipeline ./pipeline
COPY data ./data

ENV PYTHONUNBUFFERED=1
ENV PYTHONPATH=/app

CMD ["python", "-m", "pipeline.jobs.main"]
